[project]
name = "simputils-emoji"
version = "0.1.0"
description = "Simple utils to work with unicode emoji data"
requires-python = ">=3.14"
#dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["simputils", "helpers", "emoji", "unicode", "utf"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
authors = [
    { name = "PandaHugMonster", email = "ivan.ponomarev.pi@gmail.com" }
]

dependencies = []

[build-system]
requires = [
    "setuptools>=64",
    "setuptools_scm>=8"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["simputils.emoji"]
#
#[build-system]
#requires = ["uv_build>=0.9.18,<0.10.0"]
#build-backend = "uv_build"
#
#[tool.uv.sources]
#simputils = { path = "./simputils/emoji" }